services:
  api:
    build:
      context: .
      no_cache: true
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=simpledb
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASSWORD=admin
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simpledb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: